<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class _paket extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('_paket_model');
    } 

    /*
     * Listing of _paket
     */
    function index()
    {
        $data['_paket'] = $this->_paket_model->get_all__paket();
        
        $data['_view'] = '_paket/index';
    

        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('_paket/index',$data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new _paket
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_keterangan' => $this->input->post('id_keterangan'),
				'id_penyedia' => $this->input->post('id_penyedia'),
				'id_progress' => $this->input->post('id_progress'),
				'id_ktgori_pengadaan' => $this->input->post('id_ktgori_pengadaan'),
				'sumberdana' => $this->input->post('sumberdana'),
				'volume' => $this->input->post('volume'),
				'tgl_kebutuhan' => $this->input->post('tgl_kebutuhan'),
				'tgl_awal_pkerjaan' => $this->input->post('tgl_awal_pkerjaan'),
				'tgl_akhir_pkerjaan' => $this->input->post('tgl_akhir_pkerjaan'),
				'tgl_awal_pengadaan' => $this->input->post('tgl_awal_pengadaan'),
				'tgl_akhir_pengadaan' => $this->input->post('tgl_akhir_pengadaan'),
				'jenis' => $this->input->post('jenis'),
				'metode' => $this->input->post('metode'),
				'uraian' => $this->input->post('uraian'),
				'tahun_anggaran' => $this->input->post('tahun_anggaran'),
				'createtime' => $this->input->post('createtime'),
				'nama_paket' => $this->input->post('nama_paket'),
				'rincian_paket' => $this->input->post('rincian_paket'),
				'detail_paket' => $this->input->post('detail_paket'),
				'uang_paket' => $this->input->post('uang_paket'),
            );
            
            $_paket_id = $this->_paket_model->add__paket($params);
            redirect('_paket/index');
        }
        else
        {
			$this->load->model('_keterangan_model');
			$data['all__keterangan'] = $this->_keterangan_model->get_all__keterangan();

			$this->load->model('penyedium_model');
			$data['all__penyedia'] = $this->penyedium_model->get_all_penyedia();

			// $this->load->model('Progres_model');
			// $data['all_progress'] = $this->Progres_model->get_all_progress();
            
            $data['_view'] = '_paket/add';
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('_paket/add',$data);
            $this->load->view('template/footer');
        }
    }  

    /*
     * Editing a _paket
     */
    function edit($id_paket)
    {   
        // check if the _paket exists before trying to edit it
        $data['_paket'] = $this->_paket_model->get__paket($id_paket);
        
        if(isset($data['_paket']['id_paket']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_keterangan' => $this->input->post('id_keterangan'),
					'id_penyedia' => $this->input->post('id_penyedia'),
					'id_progress' => $this->input->post('id_progress'),
					'id_ktgori_pengadaan' => $this->input->post('id_ktgori_pengadaan'),
					'sumberdana' => $this->input->post('sumberdana'),
					'volume' => $this->input->post('volume'),
					'tgl_kebutuhan' => $this->input->post('tgl_kebutuhan'),
					'tgl_awal_pkerjaan' => $this->input->post('tgl_awal_pkerjaan'),
					'tgl_akhir_pkerjaan' => $this->input->post('tgl_akhir_pkerjaan'),
					'tgl_awal_pengadaan' => $this->input->post('tgl_awal_pengadaan'),
					'tgl_akhir_pengadaan' => $this->input->post('tgl_akhir_pengadaan'),
					'jenis' => $this->input->post('jenis'),
					'metode' => $this->input->post('metode'),
					'uraian' => $this->input->post('uraian'),
					'tahun_anggaran' => $this->input->post('tahun_anggaran'),
					'createtime' => $this->input->post('createtime'),
					'nama_paket' => $this->input->post('nama_paket'),
					'rincian_paket' => $this->input->post('rincian_paket'),
					'detail_paket' => $this->input->post('detail_paket'),
					'uang_paket' => $this->input->post('uang_paket'),
                );

                $this->_paket_model->update__paket($id_paket,$params);            
                redirect('_paket/index');
            }
            else
            {
				$this->load->model('_keterangan_model');
				$data['all__keterangan'] = $this->_keterangan_model->get_all__keterangan();

				$this->load->model('penyedium_model');
				$data['all__penyedia'] = $this->penyedium_model->get_all_penyedia();

				$this->load->model('Progres_model');
				$data['all_progress'] = $this->Progres_model->get_all_progress();

                $data['_view'] = '_paket/edit';
                 $this->load->view('template/header');
                $this->load->view('template/sidebar');
                $this->load->view('_paket/edit',$data);
                $this->load->view('template/footer');
               
            }
                
        }
        else
            show_error('The _paket you are trying to edit does not exist.');
    } 

    /*
     * Deleting _paket
     */
    function remove($id_paket)
    {
        $_paket = $this->_paket_model->get__paket($id_paket);

        // check if the _paket exists before trying to delete it
        if(isset($_paket['id_paket']))
        {
            $this->_paket_model->delete__paket($id_paket);
            redirect('_paket/index');
        }
        else
            show_error('The _paket you are trying to delete does not exist.');
    }
    
}
