<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_lokasi_paket extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tr_lokasi_paket_model');
    } 

    /*
     * Listing of tr_lokasi_paket
     */
    function index()
    {
        $data['tr_lokasi_paket'] = $this->Tr_lokasi_paket_model->get_all_tr_lokasi_paket();
        
        $data['_view'] = 'tr_lokasi_paket/index';
        //$this->load->view('layouts/main',$data);
        $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('tr_lokasi_paket/index',$data);
        $this->load->view('template/footer');
    }

    /*
     * Adding a new tr_lokasi_paket
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_paket' => $this->input->post('id_paket'),
				'id_kec_kel' => $this->input->post('id_kec_kel'),
				'keterangan' => $this->input->post('keterangan'),
				'createdDate' => $this->input->post('createdDate'),
            );
            
            $tr_lokasi_paket_id = $this->Tr_lokasi_paket_model->add_tr_lokasi_paket($params);
            redirect('test-bootstrap/_paket/edit/'.$this->input->post('id_paket'));
        }
        else
        {
			$this->load->model('_paket_model');
			$data['all__paket'] = $this->_paket_model->get_all__paket();

			$this->load->model('Kec_kel_model');
			$data['all_kec_kel'] = $this->Kec_kel_model->get_all_kec_kel();
            
            $data['_view'] = 'tr_lokasi_paket/add';
            //$this->load->view('layouts/main',$data);
            $this->load->view('template/header');
            $this->load->view('template/sidebar');
            $this->load->view('tr_lokasi_paket/add',$data);
            $this->load->view('template/footer');

        }
    }  

    /*
     * Editing a tr_lokasi_paket
     */
    function edit($id)
    {   
        // check if the tr_lokasi_paket exists before trying to edit it
        $data['tr_lokasi_paket'] = $this->Tr_lokasi_paket_model->get_tr_lokasi_paket($id);
        
        if(isset($data['tr_lokasi_paket']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_paket' => $this->input->post('id_paket'),
					'id_kec_kel' => $this->input->post('id_kec_kel'),
					'keterangan' => $this->input->post('keterangan'),
					'createdDate' => $this->input->post('createdDate'),
                );

                $this->Tr_lokasi_paket_model->update_tr_lokasi_paket($id,$params);            
                // redirect('test-bootstrap/_paket/index');
                $this->load->model('_paket_model');
                $data = $this->_paket_model->get_id_paket_l();
                redirect('test-bootstrap/_paket/edit/'.$data['id_paket']);
            }
            else
            {
				$this->load->model('_paket_model');
				$data['all__paket'] = $this->_paket_model->get_all__paket();

				$this->load->model('Kec_kel_model');
				$data['all_kec_kel'] = $this->Kec_kel_model->get_all_kec_kel();

                $data['_view'] = 'tr_lokasi_paket/edit';
                //$this->load->view('layouts/main',$data);
                $this->load->view('template/header');
        $this->load->view('template/sidebar');
        $this->load->view('tr_lokasi_paket/edit',$data);
        $this->load->view('template/footer');
            }
        }
        else
            show_error('The tr_lokasi_paket you are trying to edit does not exist.');
    } 

    /*
     * Deleting tr_lokasi_paket
     */
    function remove($id)
    {
        $tr_lokasi_paket = $this->Tr_lokasi_paket_model->get_tr_lokasi_paket($id);

        // check if the tr_lokasi_paket exists before trying to delete it
        if(isset($tr_lokasi_paket['id']))
        {
            $this->Tr_lokasi_paket_model->delete_tr_lokasi_paket($id);
            redirect('tr_lokasi_paket/index');
        }
        else
            show_error('The tr_lokasi_paket you are trying to delete does not exist.');
    }
    
}