<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class _kegiatan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get _kegiatan by id_kegiatan
     */
    function get__kegiatan($id_kegiatan)
    {
        return $this->db->get_where('_kegiatan',array('id_kegiatan'=>$id_kegiatan))->row_array();
    }
        
    /*
     * Get all _kegiatan
     */
    function get_all__kegiatan()
    {
        $this->db->order_by('id_kegiatan', 'desc');
        return $this->db->get('_kegiatan')->result_array();
    }
        
    /*
     * function to add new _kegiatan
     */
    function add__kegiatan($params)
    {
        $this->db->insert('_kegiatan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update _kegiatan
     */
    function update__kegiatan($id_kegiatan,$params)
    {
        $this->db->where('id_kegiatan',$id_kegiatan);
        return $this->db->update('_kegiatan',$params);
    }
    
    /*
     * function to delete _kegiatan
     */
    function delete__kegiatan($id_kegiatan)
    {
        return $this->db->delete('_kegiatan',array('id_kegiatan'=>$id_kegiatan));
    }
}
