<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class _paket_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get _paket by id_paket
     */
    function get__paket($id_paket)
    {
        return $this->db->get_where('_paket',array('id_paket'=>$id_paket))->row_array();
    }
        
    /*
     * Get all _paket
     */
    function get_all__paket()
    {
        $this->db->order_by('id_paket', 'desc');
        return $this->db->get('_paket')->result_array();
    }
        
    /*
     * function to add new _paket
     */
    function add__paket($params)
    {
        $this->db->insert('_paket',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update _paket
     */
    function update__paket($id_paket,$params)
    {
        $this->db->where('id_paket',$id_paket);
        return $this->db->update('_paket',$params);
    }
    
    /*
     * function to delete _paket
     */
    function delete__paket($id_paket)
    {
        return $this->db->delete('_paket',array('id_paket'=>$id_paket));
    }
}
