<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class _penyedium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get _penyedium by id_penyedia
     */
    function get__penyedium($id_penyedia)
    {
        return $this->db->get_where('_penyedia',array('id_penyedia'=>$id_penyedia))->row_array();
    }
        
    /*
     * Get all _penyedia
     */
    function get_all__penyedia()
    {
        $this->db->order_by('id_penyedia', 'desc');
        return $this->db->get('_penyedia')->result_array();
    }
        
    /*
     * function to add new _penyedium
     */
    function add__penyedium($params)
    {
        $this->db->insert('_penyedia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update _penyedium
     */
    function update__penyedium($id_penyedia,$params)
    {
        $this->db->where('id_penyedia',$id_penyedia);
        return $this->db->update('_penyedia',$params);
    }
    
    /*
     * function to delete _penyedium
     */
    function delete__penyedium($id_penyedia)
    {
        return $this->db->delete('_penyedia',array('id_penyedia'=>$id_penyedia));
    }
}
