<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fungsi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get fungsi by id_fungsi
     */
    function get_fungsi($id_fungsi)
    {
        return $this->db->get_where('fungsi',array('id_fungsi'=>$id_fungsi))->row_array();
    }
        
    /*
     * Get all fungsi
     */
    function get_all_fungsi()
    {
        $this->db->order_by('id_fungsi', 'desc');
        return $this->db->get('fungsi')->result_array();
    }
        
    /*
     * function to add new fungsi
     */
    function add_fungsi($params)
    {
        $this->db->insert('fungsi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update fungsi
     */
    function update_fungsi($id_fungsi,$params)
    {
        $this->db->where('id_fungsi',$id_fungsi);
        return $this->db->update('fungsi',$params);
    }
    
    /*
     * function to delete fungsi
     */
    function delete_fungsi($id_fungsi)
    {
        return $this->db->delete('fungsi',array('id_fungsi'=>$id_fungsi));
    }
}
