<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jeni_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jeni by id_jenis
     */
    function get_jeni($id_jenis)
    {
        return $this->db->get_where('jenis',array('id_jenis'=>$id_jenis))->row_array();
    }
        
    /*
     * Get all jenis
     */
    function get_all_jenis()
    {
        $this->db->order_by('id_jenis', 'desc');
        return $this->db->get('jenis')->result_array();
    }
        
    /*
     * function to add new jeni
     */
    function add_jeni($params)
    {
        $this->db->insert('jenis',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jeni
     */
    function update_jeni($id_jenis,$params)
    {
        $this->db->where('id_jenis',$id_jenis);
        return $this->db->update('jenis',$params);
    }
    
    /*
     * function to delete jeni
     */
    function delete_jeni($id_jenis)
    {
        return $this->db->delete('jenis',array('id_jenis'=>$id_jenis));
    }
}
