<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mas_pak_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mas_pak by id_master
     */
    function get_mas_pak($id_master)
    {
        return $this->db->get_where('mas_pak',array('id_master'=>$id_master))->row_array();
    }
        
    /*
     * Get all mas_pak
     */
    function get_all_mas_pak()
    {
        $this->db->order_by('id_master', 'desc');
        return $this->db->get('mas_pak')->result_array();
    }
        
    /*
     * function to add new mas_pak
     */
    function add_mas_pak($params)
    {
        $this->db->insert('mas_pak',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mas_pak
     */
    function update_mas_pak($id_master,$params)
    {
        $this->db->where('id_master',$id_master);
        return $this->db->update('mas_pak',$params);
    }
    
    /*
     * function to delete mas_pak
     */
    function delete_mas_pak($id_master)
    {
        return $this->db->delete('mas_pak',array('id_master'=>$id_master));
    }
}
