<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Master_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get master by id_master
     */
    function get_master($id_master)
    {
        return $this->db->get_where('master',array('id_master'=>$id_master))->row_array();
    }
        
    /*
     * Get all master
     */
    function get_all_master()
    {
        $this->db->order_by('id_master', 'desc');
        return $this->db->get('master')->result_array();
    }
        
    /*
     * function to add new master
     */
    function add_master($params)
    {
        $this->db->insert('master',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update master
     */
    function update_master($id_master,$params)
    {
        $this->db->where('id_master',$id_master);
        return $this->db->update('master',$params);
    }
    
    /*
     * function to delete master
     */
    function delete_master($id_master)
    {
        return $this->db->delete('master',array('id_master'=>$id_master));
    }
}
