<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Metode_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get metode by id_metode
     */
    function get_metode($id_metode)
    {
        return $this->db->get_where('metode',array('id_metode'=>$id_metode))->row_array();
    }
        
    /*
     * Get all metode
     */
    function get_all_metode()
    {
        $this->db->order_by('id_metode', 'desc');
        return $this->db->get('metode')->result_array();
    }
        
    /*
     * function to add new metode
     */
    function add_metode($params)
    {
        $this->db->insert('metode',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update metode
     */
    function update_metode($id_metode,$params)
    {
        $this->db->where('id_metode',$id_metode);
        return $this->db->update('metode',$params);
    }
    
    /*
     * function to delete metode
     */
    function delete_metode($id_metode)
    {
        return $this->db->delete('metode',array('id_metode'=>$id_metode));
    }
}
