<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ppk_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ppk by id_ppk
     */
    function get_ppk($id_ppk)
    {
        return $this->db->get_where('ppk',array('id_ppk'=>$id_ppk))->row_array();
    }
        
    /*
     * Get all ppk
     */
    function get_all_ppk()
    {
        $this->db->order_by('id_ppk', 'desc');
        return $this->db->get('ppk')->result_array();
    }
        
    /*
     * function to add new ppk
     */
    function add_ppk($params)
    {
        $this->db->insert('ppk',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ppk
     */
    function update_ppk($id_ppk,$params)
    {
        $this->db->where('id_ppk',$id_ppk);
        return $this->db->update('ppk',$params);
    }
    
    /*
     * function to delete ppk
     */
    function delete_ppk($id_ppk)
    {
        return $this->db->delete('ppk',array('id_ppk'=>$id_ppk));
    }
}
