<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Progress_swklola_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get progress_swklola by id_prog_swklola
     */
    function get_progress_swklola($id_prog_swklola)
    {
        return $this->db->get_where('progress_swklola',array('id_prog_swklola'=>$id_prog_swklola))->row_array();
    }
        
    /*
     * Get all progress_swklola
     */
    function get_all_progress_swklola()
    {
        $this->db->order_by('id_prog_swklola', 'desc');
        return $this->db->get('progress_swklola')->result_array();
    }
        
    /*
     * function to add new progress_swklola
     */
    function add_progress_swklola($params)
    {
        $this->db->insert('progress_swklola',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update progress_swklola
     */
    function update_progress_swklola($id_prog_swklola,$params)
    {
        $this->db->where('id_prog_swklola',$id_prog_swklola);
        return $this->db->update('progress_swklola',$params);
    }
    
    /*
     * function to delete progress_swklola
     */
    function delete_progress_swklola($id_prog_swklola)
    {
        return $this->db->delete('progress_swklola',array('id_prog_swklola'=>$id_prog_swklola));
    }
}
