<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Progress_penyedium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get progress_penyedium by id_progress_penyedia
     */
    function get_progress_penyedium($id_progress_penyedia)
    {
        return $this->db->get_where('progress_penyedia',array('id_progress_penyedia'=>$id_progress_penyedia))->row_array();
    }
        
    /*
     * Get all progress_penyedia
     */
    function get_all_progress_penyedia()
    {
        $this->db->order_by('id_progress_penyedia', 'desc');
        return $this->db->get('progress_penyedia')->result_array();
    }
        
    /*
     * function to add new progress_penyedium
     */
    function add_progress_penyedium($params)
    {
        $this->db->insert('progress_penyedia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update progress_penyedium
     */
    function update_progress_penyedium($id_progress_penyedia,$params)
    {
        $this->db->where('id_progress_penyedia',$id_progress_penyedia);
        return $this->db->update('progress_penyedia',$params);
    }
    
    /*
     * function to delete progress_penyedium
     */
    function delete_progress_penyedium($id_progress_penyedia)
    {
        return $this->db->delete('progress_penyedia',array('id_progress_penyedia'=>$id_progress_penyedia));
    }
}
