<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ref_rek_4_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ref_rek_4 by Kd_Rek_1
     */
    function get_ref_rek_4($Kd_Rek_1)
    {
        return $this->db->get_where('ref_rek_4',array('Kd_Rek_1'=>$Kd_Rek_1))->row_array();
    }
        
    /*
     * Get all ref_rek_4
     */
    function get_all_ref_rek_4()
    {
        $this->db->order_by('Kd_Rek_1', 'desc');
        return $this->db->get('ref_rek_4')->result_array();
    }
        
    /*
     * function to add new ref_rek_4
     */
    function add_ref_rek_4($params)
    {
        $this->db->insert('ref_rek_4',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ref_rek_4
     */
    function update_ref_rek_4($Kd_Rek_1,$params)
    {
        $this->db->where('Kd_Rek_1',$Kd_Rek_1);
        return $this->db->update('ref_rek_4',$params);
    }
    
    /*
     * function to delete ref_rek_4
     */
    function delete_ref_rek_4($Kd_Rek_1)
    {
        return $this->db->delete('ref_rek_4',array('Kd_Rek_1'=>$Kd_Rek_1));
    }
}
