<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rekening_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get rekening by id_rek
     */
    function get_rekening($id_rek)
    {
        return $this->db->get_where('rekening',array('id_rek'=>$id_rek))->row_array();
    }
        
    /*
     * Get all rekening
     */
    function get_all_rekening()
    {
        $this->db->order_by('id_rek', 'desc');
        return $this->db->get('rekening')->result_array();
    }
        
    /*
     * function to add new rekening
     */
    function add_rekening($params)
    {
        $this->db->insert('rekening',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update rekening
     */
    function update_rekening($id_rek,$params)
    {
        $this->db->where('id_rek',$id_rek);
        return $this->db->update('rekening',$params);
    }
    
    /*
     * function to delete rekening
     */
    function delete_rekening($id_rek)
    {
        return $this->db->delete('rekening',array('id_rek'=>$id_rek));
    }
}
