<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Statu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get statu by id_status
     */
    function get_statu($id_status)
    {
        return $this->db->get_where('status',array('id_status'=>$id_status))->row_array();
    }
        
    /*
     * Get all status
     */
    function get_all_status()
    {
        $this->db->order_by('id_status', 'desc');
        return $this->db->get('status')->result_array();
    }
        
    /*
     * function to add new statu
     */
    function add_statu($params)
    {
        $this->db->insert('status',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update statu
     */
    function update_statu($id_status,$params)
    {
        $this->db->where('id_status',$id_status);
        return $this->db->update('status',$params);
    }
    
    /*
     * function to delete statu
     */
    function delete_statu($id_status)
    {
        return $this->db->delete('status',array('id_status'=>$id_status));
    }
}
