<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Swakelola_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get swakelola by id_p_swakelola
     */
    function get_swakelola($id_p_swakelola)
    {
        return $this->db->get_where('swakelola',array('id_p_swakelola'=>$id_p_swakelola))->row_array();
    }
        
    /*
     * Get all swakelola
     */
    function get_all_swakelola()
    {
        $this->db->order_by('id_p_swakelola', 'desc');
        return $this->db->get('swakelola')->result_array();
    }
        
    /*
     * function to add new swakelola
     */
    function add_swakelola($params)
    {
        $this->db->insert('swakelola',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update swakelola
     */
    function update_swakelola($id_p_swakelola,$params)
    {
        $this->db->where('id_p_swakelola',$id_p_swakelola);
        return $this->db->update('swakelola',$params);
    }
    
    /*
     * function to delete swakelola
     */
    function delete_swakelola($id_p_swakelola)
    {
        return $this->db->delete('swakelola',array('id_p_swakelola'=>$id_p_swakelola));
    }
}
