<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_belanja_rekening_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tr_belanja_rekening by 
     */
    function get_tr_belanja_rekening($)
    {
        return $this->db->get_where('tr_belanja_rekening',array(''=>$))->row_array();
    }
        
    /*
     * Get all tr_belanja_rekening
     */
    function get_all_tr_belanja_rekening()
    {
        $this->db->order_by('', 'desc');
        return $this->db->get('tr_belanja_rekening')->result_array();
    }
        
    /*
     * function to add new tr_belanja_rekening
     */
    function add_tr_belanja_rekening($params)
    {
        $this->db->insert('tr_belanja_rekening',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tr_belanja_rekening
     */
    function update_tr_belanja_rekening($,$params)
    {
        $this->db->where('',$);
        return $this->db->update('tr_belanja_rekening',$params);
    }
    
    /*
     * function to delete tr_belanja_rekening
     */
    function delete_tr_belanja_rekening($)
    {
        return $this->db->delete('tr_belanja_rekening',array(''=>$));
    }
}
