<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Unit_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get unit by id_unit
     */
    function get_unit($id_unit)
    {
        return $this->db->get_where('unit',array('id_unit'=>$id_unit))->row_array();
    }
        
    /*
     * Get all unit
     */
    function get_all_unit()
    {
        $this->db->order_by('id_unit', 'desc');
        return $this->db->get('unit')->result_array();
    }
        
    /*
     * function to add new unit
     */
    function add_unit($params)
    {
        $this->db->insert('unit',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update unit
     */
    function update_unit($id_unit,$params)
    {
        $this->db->where('id_unit',$id_unit);
        return $this->db->update('unit',$params);
    }
    
    /*
     * function to delete unit
     */
    function delete_unit($id_unit)
    {
        return $this->db->delete('unit',array('id_unit'=>$id_unit));
    }
}
