<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class _program extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('_program_model');
    } 

    /*
     * Listing of _program
     */
    function index()
    {
        $data['_program'] = $this->_program_model->get_all__program();
        
        $data['_view'] = '_program/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new _program
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_urusan' => $this->input->post('id_urusan'),
				'id_bidang' => $this->input->post('id_bidang'),
				'kd_prog' => $this->input->post('kd_prog'),
				'program' => $this->input->post('program'),
				'id_satker' => $this->input->post('id_satker'),
            );
            
            $_program_id = $this->_program_model->add__program($params);
            redirect('_program/index');
        }
        else
        {
			$this->load->model('Urusan_model');
			$data['all_urusan'] = $this->Urusan_model->get_all_urusan();
            
            $data['_view'] = '_program/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a _program
     */
    function edit($id_program)
    {   
        // check if the _program exists before trying to edit it
        $data['_program'] = $this->_program_model->get__program($id_program);
        
        if(isset($data['_program']['id_program']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_urusan' => $this->input->post('id_urusan'),
					'id_bidang' => $this->input->post('id_bidang'),
					'kd_prog' => $this->input->post('kd_prog'),
					'program' => $this->input->post('program'),
					'id_satker' => $this->input->post('id_satker'),
                );

                $this->_program_model->update__program($id_program,$params);            
                redirect('_program/index');
            }
            else
            {
				$this->load->model('Urusan_model');
				$data['all_urusan'] = $this->Urusan_model->get_all_urusan();

                $data['_view'] = '_program/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The _program you are trying to edit does not exist.');
    } 

    /*
     * Deleting _program
     */
    function remove($id_program)
    {
        $_program = $this->_program_model->get__program($id_program);

        // check if the _program exists before trying to delete it
        if(isset($_program['id_program']))
        {
            $this->_program_model->delete__program($id_program);
            redirect('_program/index');
        }
        else
            show_error('The _program you are trying to delete does not exist.');
    }
    
}
