<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Det_paket extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Det_paket_model');
    } 

    /*
     * Listing of det_paket
     */
    function index()
    {
        $data['det_paket'] = $this->Det_paket_model->get_all_det_paket();
        
        $data['_view'] = 'det_paket/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new det_paket
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_p_penyedia' => $this->input->post('id_p_penyedia'),
				'id_p_swakelola' => $this->input->post('id_p_swakelola'),
				'detail_paket' => $this->input->post('detail_paket'),
				'vol_paket' => $this->input->post('vol_paket'),
				'uang_paket' => $this->input->post('uang_paket'),
				'id_satker' => $this->input->post('id_satker'),
            );
            
            $det_paket_id = $this->Det_paket_model->add_det_paket($params);
            redirect('det_paket/index');
        }
        else
        {            
            $data['_view'] = 'det_paket/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a det_paket
     */
    function edit($id_det_paket)
    {   
        // check if the det_paket exists before trying to edit it
        $data['det_paket'] = $this->Det_paket_model->get_det_paket($id_det_paket);
        
        if(isset($data['det_paket']['id_det_paket']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_p_penyedia' => $this->input->post('id_p_penyedia'),
					'id_p_swakelola' => $this->input->post('id_p_swakelola'),
					'detail_paket' => $this->input->post('detail_paket'),
					'vol_paket' => $this->input->post('vol_paket'),
					'uang_paket' => $this->input->post('uang_paket'),
					'id_satker' => $this->input->post('id_satker'),
                );

                $this->Det_paket_model->update_det_paket($id_det_paket,$params);            
                redirect('det_paket/index');
            }
            else
            {
                $data['_view'] = 'det_paket/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The det_paket you are trying to edit does not exist.');
    } 

    /*
     * Deleting det_paket
     */
    function remove($id_det_paket)
    {
        $det_paket = $this->Det_paket_model->get_det_paket($id_det_paket);

        // check if the det_paket exists before trying to delete it
        if(isset($det_paket['id_det_paket']))
        {
            $this->Det_paket_model->delete_det_paket($id_det_paket);
            redirect('det_paket/index');
        }
        else
            show_error('The det_paket you are trying to delete does not exist.');
    }
    
}
