<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Fungsi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Fungsi_model');
    } 

    /*
     * Listing of fungsi
     */
    function index()
    {
        $data['fungsi'] = $this->Fungsi_model->get_all_fungsi();
        
        $data['_view'] = 'fungsi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new fungsi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_fungsi' => $this->input->post('nama_fungsi'),
            );
            
            $fungsi_id = $this->Fungsi_model->add_fungsi($params);
            redirect('fungsi/index');
        }
        else
        {            
            $data['_view'] = 'fungsi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a fungsi
     */
    function edit($id_fungsi)
    {   
        // check if the fungsi exists before trying to edit it
        $data['fungsi'] = $this->Fungsi_model->get_fungsi($id_fungsi);
        
        if(isset($data['fungsi']['id_fungsi']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_fungsi' => $this->input->post('nama_fungsi'),
                );

                $this->Fungsi_model->update_fungsi($id_fungsi,$params);            
                redirect('fungsi/index');
            }
            else
            {
                $data['_view'] = 'fungsi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The fungsi you are trying to edit does not exist.');
    } 

    /*
     * Deleting fungsi
     */
    function remove($id_fungsi)
    {
        $fungsi = $this->Fungsi_model->get_fungsi($id_fungsi);

        // check if the fungsi exists before trying to delete it
        if(isset($fungsi['id_fungsi']))
        {
            $this->Fungsi_model->delete_fungsi($id_fungsi);
            redirect('fungsi/index');
        }
        else
            show_error('The fungsi you are trying to delete does not exist.');
    }
    
}
