<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lokasi extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lokasi_model');
    } 

    /*
     * Listing of lokasi
     */
    function index()
    {
        $data['lokasi'] = $this->Lokasi_model->get_all_lokasi();
        
        $data['_view'] = 'lokasi/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lokasi
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_paket_lokasi' => $this->input->post('id_paket_lokasi'),
				'kec' => $this->input->post('kec'),
				'kel' => $this->input->post('kel'),
				'detail_lok' => $this->input->post('detail_lok'),
            );
            
            $lokasi_id = $this->Lokasi_model->add_lokasi($params);
            redirect('lokasi/index');
        }
        else
        {            
            $data['_view'] = 'lokasi/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lokasi
     */
    function edit($id_lokasi)
    {   
        // check if the lokasi exists before trying to edit it
        $data['lokasi'] = $this->Lokasi_model->get_lokasi($id_lokasi);
        
        if(isset($data['lokasi']['id_lokasi']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_paket_lokasi' => $this->input->post('id_paket_lokasi'),
					'kec' => $this->input->post('kec'),
					'kel' => $this->input->post('kel'),
					'detail_lok' => $this->input->post('detail_lok'),
                );

                $this->Lokasi_model->update_lokasi($id_lokasi,$params);            
                redirect('lokasi/index');
            }
            else
            {
                $data['_view'] = 'lokasi/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lokasi you are trying to edit does not exist.');
    } 

    /*
     * Deleting lokasi
     */
    function remove($id_lokasi)
    {
        $lokasi = $this->Lokasi_model->get_lokasi($id_lokasi);

        // check if the lokasi exists before trying to delete it
        if(isset($lokasi['id_lokasi']))
        {
            $this->Lokasi_model->delete_lokasi($id_lokasi);
            redirect('lokasi/index');
        }
        else
            show_error('The lokasi you are trying to delete does not exist.');
    }
    
}
