<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mas_pak extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mas_pak_model');
    } 

    /*
     * Listing of mas_pak
     */
    function index()
    {
        $data['mas_pak'] = $this->Mas_pak_model->get_all_mas_pak();
        
        $data['_view'] = 'mas_pak/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new mas_pak
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
            );
            
            $mas_pak_id = $this->Mas_pak_model->add_mas_pak($params);
            redirect('mas_pak/index');
        }
        else
        {            
            $data['_view'] = 'mas_pak/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a mas_pak
     */
    function edit($id_master)
    {   
        // check if the mas_pak exists before trying to edit it
        $data['mas_pak'] = $this->Mas_pak_model->get_mas_pak($id_master);
        
        if(isset($data['mas_pak']['id_master']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
                );

                $this->Mas_pak_model->update_mas_pak($id_master,$params);            
                redirect('mas_pak/index');
            }
            else
            {
                $data['_view'] = 'mas_pak/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The mas_pak you are trying to edit does not exist.');
    } 

    /*
     * Deleting mas_pak
     */
    function remove($id_master)
    {
        $mas_pak = $this->Mas_pak_model->get_mas_pak($id_master);

        // check if the mas_pak exists before trying to delete it
        if(isset($mas_pak['id_master']))
        {
            $this->Mas_pak_model->delete_mas_pak($id_master);
            redirect('mas_pak/index');
        }
        else
            show_error('The mas_pak you are trying to delete does not exist.');
    }
    
}
