<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Penyedium extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Penyedium_model');
    } 

    /*
     * Listing of penyedia
     */
    function index()
    {
        $data['penyedia'] = $this->Penyedium_model->get_all_penyedia();
        
        $data['_view'] = 'penyedium/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new penyedium
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_swakelola' => $this->input->post('id_swakelola'),
				'tanggal_terakhir_di_update' => $this->input->post('tanggal_terakhir_di_update'),
				'status_aktif' => $this->input->post('status_aktif'),
				'id_satker' => $this->input->post('id_satker'),
				'nama_satker' => $this->input->post('nama_satker'),
				'program' => $this->input->post('program'),
				'kegiatan' => $this->input->post('kegiatan'),
				'nama_paket' => $this->input->post('nama_paket'),
				'volume' => $this->input->post('volume'),
				'jenis_pengadaan' => $this->input->post('jenis_pengadaan'),
				'metode_pemilihan' => $this->input->post('metode_pemilihan'),
				'sumber_dana' => $this->input->post('sumber_dana'),
				'detail_sumberdana' => $this->input->post('detail_sumberdana'),
				'kecamatan' => $this->input->post('kecamatan'),
				'kelurahan' => $this->input->post('kelurahan'),
				'detail_lokasi' => $this->input->post('detail_lokasi'),
				'pagu_rup' => $this->input->post('pagu_rup'),
				'hps_penyedia' => $this->input->post('hps_penyedia'),
				'nilai_kontrak' => $this->input->post('nilai_kontrak'),
				'sisa_pagu' => $this->input->post('sisa_pagu'),
				'awal_pengadaan' => $this->input->post('awal_pengadaan'),
				'akhir_pengadaan' => $this->input->post('akhir_pengadaan'),
				'awal_pekerjaan' => $this->input->post('awal_pekerjaan'),
				'akhir_pekerjaan' => $this->input->post('akhir_pekerjaan'),
				'tanggal_kebutuhan' => $this->input->post('tanggal_kebutuhan'),
				'nama_ppk' => $this->input->post('nama_ppk'),
				'nip_ppk' => $this->input->post('nip_ppk'),
				'spesifikasi' => $this->input->post('spesifikasi'),
            );
            
            $penyedium_id = $this->Penyedium_model->add_penyedium($params);
            redirect('penyedium/index');
        }
        else
        {            
            $data['_view'] = 'penyedium/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a penyedium
     */
    function edit($id_p_progress)
    {   
        // check if the penyedium exists before trying to edit it
        $data['penyedium'] = $this->Penyedium_model->get_penyedium($id_p_progress);
        
        if(isset($data['penyedium']['id_p_progress']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_swakelola' => $this->input->post('id_swakelola'),
					'tanggal_terakhir_di_update' => $this->input->post('tanggal_terakhir_di_update'),
					'status_aktif' => $this->input->post('status_aktif'),
					'id_satker' => $this->input->post('id_satker'),
					'nama_satker' => $this->input->post('nama_satker'),
					'program' => $this->input->post('program'),
					'kegiatan' => $this->input->post('kegiatan'),
					'nama_paket' => $this->input->post('nama_paket'),
					'volume' => $this->input->post('volume'),
					'jenis_pengadaan' => $this->input->post('jenis_pengadaan'),
					'metode_pemilihan' => $this->input->post('metode_pemilihan'),
					'sumber_dana' => $this->input->post('sumber_dana'),
					'detail_sumberdana' => $this->input->post('detail_sumberdana'),
					'kecamatan' => $this->input->post('kecamatan'),
					'kelurahan' => $this->input->post('kelurahan'),
					'detail_lokasi' => $this->input->post('detail_lokasi'),
					'pagu_rup' => $this->input->post('pagu_rup'),
					'hps_penyedia' => $this->input->post('hps_penyedia'),
					'nilai_kontrak' => $this->input->post('nilai_kontrak'),
					'sisa_pagu' => $this->input->post('sisa_pagu'),
					'awal_pengadaan' => $this->input->post('awal_pengadaan'),
					'akhir_pengadaan' => $this->input->post('akhir_pengadaan'),
					'awal_pekerjaan' => $this->input->post('awal_pekerjaan'),
					'akhir_pekerjaan' => $this->input->post('akhir_pekerjaan'),
					'tanggal_kebutuhan' => $this->input->post('tanggal_kebutuhan'),
					'nama_ppk' => $this->input->post('nama_ppk'),
					'nip_ppk' => $this->input->post('nip_ppk'),
					'spesifikasi' => $this->input->post('spesifikasi'),
                );

                $this->Penyedium_model->update_penyedium($id_p_progress,$params);            
                redirect('penyedium/index');
            }
            else
            {
                $data['_view'] = 'penyedium/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The penyedium you are trying to edit does not exist.');
    } 

    /*
     * Deleting penyedium
     */
    function remove($id_p_progress)
    {
        $penyedium = $this->Penyedium_model->get_penyedium($id_p_progress);

        // check if the penyedium exists before trying to delete it
        if(isset($penyedium['id_p_progress']))
        {
            $this->Penyedium_model->delete_penyedium($id_p_progress);
            redirect('penyedium/index');
        }
        else
            show_error('The penyedium you are trying to delete does not exist.');
    }
    
}
