<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Progres extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Progres_model');
    } 

    /*
     * Listing of progress
     */
    function index()
    {
        $data['progress'] = $this->Progres_model->get_all_progress();
        
        $data['_view'] = 'progres/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new progres
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_progress_penyedia' => $this->input->post('id_progress_penyedia'),
				'id_progeress_swklola' => $this->input->post('id_progeress_swklola'),
            );
            
            $progres_id = $this->Progres_model->add_progres($params);
            redirect('progres/index');
        }
        else
        {            
            $data['_view'] = 'progres/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a progres
     */
    function edit($id_progress)
    {   
        // check if the progres exists before trying to edit it
        $data['progres'] = $this->Progres_model->get_progres($id_progress);
        
        if(isset($data['progres']['id_progress']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_progress_penyedia' => $this->input->post('id_progress_penyedia'),
					'id_progeress_swklola' => $this->input->post('id_progeress_swklola'),
                );

                $this->Progres_model->update_progres($id_progress,$params);            
                redirect('progres/index');
            }
            else
            {
                $data['_view'] = 'progres/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The progres you are trying to edit does not exist.');
    } 

    /*
     * Deleting progres
     */
    function remove($id_progress)
    {
        $progres = $this->Progres_model->get_progres($id_progress);

        // check if the progres exists before trying to delete it
        if(isset($progres['id_progress']))
        {
            $this->Progres_model->delete_progres($id_progress);
            redirect('progres/index');
        }
        else
            show_error('The progres you are trying to delete does not exist.');
    }
    
}
