<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Progress_penyedium extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Progress_penyedium_model');
    } 

    /*
     * Listing of progress_penyedia
     */
    function index()
    {
        $data['progress_penyedia'] = $this->Progress_penyedium_model->get_all_progress_penyedia();
        
        $data['_view'] = 'progress_penyedium/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new progress_penyedium
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'bulan_realisasi' => $this->input->post('bulan_realisasi'),
				'rencana_keuangan' => $this->input->post('rencana_keuangan'),
				'ren_keuangan_persen' => $this->input->post('ren_keuangan_persen'),
				'realisasi_keuangan' => $this->input->post('realisasi_keuangan'),
				'rea_keuangan_persen' => $this->input->post('rea_keuangan_persen'),
				'rencana_fisik' => $this->input->post('rencana_fisik'),
				'ren_fisik_volume' => $this->input->post('ren_fisik_volume'),
				'realisasi_fisik' => $this->input->post('realisasi_fisik'),
				'rea_fisik_volume' => $this->input->post('rea_fisik_volume'),
				'realisasi_fisik_foto' => $this->input->post('realisasi_fisik_foto'),
				'tahapan_prgres_pnyedia' => $this->input->post('tahapan_prgres_pnyedia'),
				'no_kontrak' => $this->input->post('no_kontrak'),
				'tgl_kontrak' => $this->input->post('tgl_kontrak'),
				'nama_pelaksana' => $this->input->post('nama_pelaksana'),
				'alamat_pelaksana' => $this->input->post('alamat_pelaksana'),
				'id_p_penyedia' => $this->input->post('id_p_penyedia'),
				'id_dinas' => $this->input->post('id_dinas'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $progress_penyedium_id = $this->Progress_penyedium_model->add_progress_penyedium($params);
            redirect('progress_penyedium/index');
        }
        else
        {            
            $data['_view'] = 'progress_penyedium/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a progress_penyedium
     */
    function edit($id_progress_penyedia)
    {   
        // check if the progress_penyedium exists before trying to edit it
        $data['progress_penyedium'] = $this->Progress_penyedium_model->get_progress_penyedium($id_progress_penyedia);
        
        if(isset($data['progress_penyedium']['id_progress_penyedia']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'bulan_realisasi' => $this->input->post('bulan_realisasi'),
					'rencana_keuangan' => $this->input->post('rencana_keuangan'),
					'ren_keuangan_persen' => $this->input->post('ren_keuangan_persen'),
					'realisasi_keuangan' => $this->input->post('realisasi_keuangan'),
					'rea_keuangan_persen' => $this->input->post('rea_keuangan_persen'),
					'rencana_fisik' => $this->input->post('rencana_fisik'),
					'ren_fisik_volume' => $this->input->post('ren_fisik_volume'),
					'realisasi_fisik' => $this->input->post('realisasi_fisik'),
					'rea_fisik_volume' => $this->input->post('rea_fisik_volume'),
					'realisasi_fisik_foto' => $this->input->post('realisasi_fisik_foto'),
					'tahapan_prgres_pnyedia' => $this->input->post('tahapan_prgres_pnyedia'),
					'no_kontrak' => $this->input->post('no_kontrak'),
					'tgl_kontrak' => $this->input->post('tgl_kontrak'),
					'nama_pelaksana' => $this->input->post('nama_pelaksana'),
					'alamat_pelaksana' => $this->input->post('alamat_pelaksana'),
					'id_p_penyedia' => $this->input->post('id_p_penyedia'),
					'id_dinas' => $this->input->post('id_dinas'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Progress_penyedium_model->update_progress_penyedium($id_progress_penyedia,$params);            
                redirect('progress_penyedium/index');
            }
            else
            {
                $data['_view'] = 'progress_penyedium/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The progress_penyedium you are trying to edit does not exist.');
    } 

    /*
     * Deleting progress_penyedium
     */
    function remove($id_progress_penyedia)
    {
        $progress_penyedium = $this->Progress_penyedium_model->get_progress_penyedium($id_progress_penyedia);

        // check if the progress_penyedium exists before trying to delete it
        if(isset($progress_penyedium['id_progress_penyedia']))
        {
            $this->Progress_penyedium_model->delete_progress_penyedium($id_progress_penyedia);
            redirect('progress_penyedium/index');
        }
        else
            show_error('The progress_penyedium you are trying to delete does not exist.');
    }
    
}
