<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Progress_swklola extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Progress_swklola_model');
    } 

    /*
     * Listing of progress_swklola
     */
    function index()
    {
        $data['progress_swklola'] = $this->Progress_swklola_model->get_all_progress_swklola();
        
        $data['_view'] = 'progress_swklola/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new progress_swklola
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'bulan_realisasi' => $this->input->post('bulan_realisasi'),
				'rencana_keuangan' => $this->input->post('rencana_keuangan'),
				'realisasi_keuangan' => $this->input->post('realisasi_keuangan'),
				'rencana_fisik' => $this->input->post('rencana_fisik'),
				'realisasi_fisik' => $this->input->post('realisasi_fisik'),
				'realisasi_fisik_foto' => $this->input->post('realisasi_fisik_foto'),
				'tahapan_prgres_swklola' => $this->input->post('tahapan_prgres_swklola'),
				'no_kontrak' => $this->input->post('no_kontrak'),
				'nama_pelaksana' => $this->input->post('nama_pelaksana'),
				'alamat_pelaksana' => $this->input->post('alamat_pelaksana'),
				'id_pgr_swakelola' => $this->input->post('id_pgr_swakelola'),
				'id_dinas' => $this->input->post('id_dinas'),
				'keterangan' => $this->input->post('keterangan'),
            );
            
            $progress_swklola_id = $this->Progress_swklola_model->add_progress_swklola($params);
            redirect('progress_swklola/index');
        }
        else
        {            
            $data['_view'] = 'progress_swklola/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a progress_swklola
     */
    function edit($id_prog_swklola)
    {   
        // check if the progress_swklola exists before trying to edit it
        $data['progress_swklola'] = $this->Progress_swklola_model->get_progress_swklola($id_prog_swklola);
        
        if(isset($data['progress_swklola']['id_prog_swklola']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'bulan_realisasi' => $this->input->post('bulan_realisasi'),
					'rencana_keuangan' => $this->input->post('rencana_keuangan'),
					'realisasi_keuangan' => $this->input->post('realisasi_keuangan'),
					'rencana_fisik' => $this->input->post('rencana_fisik'),
					'realisasi_fisik' => $this->input->post('realisasi_fisik'),
					'realisasi_fisik_foto' => $this->input->post('realisasi_fisik_foto'),
					'tahapan_prgres_swklola' => $this->input->post('tahapan_prgres_swklola'),
					'no_kontrak' => $this->input->post('no_kontrak'),
					'nama_pelaksana' => $this->input->post('nama_pelaksana'),
					'alamat_pelaksana' => $this->input->post('alamat_pelaksana'),
					'id_pgr_swakelola' => $this->input->post('id_pgr_swakelola'),
					'id_dinas' => $this->input->post('id_dinas'),
					'keterangan' => $this->input->post('keterangan'),
                );

                $this->Progress_swklola_model->update_progress_swklola($id_prog_swklola,$params);            
                redirect('progress_swklola/index');
            }
            else
            {
                $data['_view'] = 'progress_swklola/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The progress_swklola you are trying to edit does not exist.');
    } 

    /*
     * Deleting progress_swklola
     */
    function remove($id_prog_swklola)
    {
        $progress_swklola = $this->Progress_swklola_model->get_progress_swklola($id_prog_swklola);

        // check if the progress_swklola exists before trying to delete it
        if(isset($progress_swklola['id_prog_swklola']))
        {
            $this->Progress_swklola_model->delete_progress_swklola($id_prog_swklola);
            redirect('progress_swklola/index');
        }
        else
            show_error('The progress_swklola you are trying to delete does not exist.');
    }
    
}
