<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Rekening extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Rekening_model');
    } 

    /*
     * Listing of rekening
     */
    function index()
    {
        $data['rekening'] = $this->Rekening_model->get_all_rekening();
        
        $data['_view'] = 'rekening/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new rekening
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_rekening' => $this->input->post('nama_rekening'),
            );
            
            $rekening_id = $this->Rekening_model->add_rekening($params);
            redirect('rekening/index');
        }
        else
        {            
            $data['_view'] = 'rekening/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a rekening
     */
    function edit($id_rek)
    {   
        // check if the rekening exists before trying to edit it
        $data['rekening'] = $this->Rekening_model->get_rekening($id_rek);
        
        if(isset($data['rekening']['id_rek']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_rekening' => $this->input->post('nama_rekening'),
                );

                $this->Rekening_model->update_rekening($id_rek,$params);            
                redirect('rekening/index');
            }
            else
            {
                $data['_view'] = 'rekening/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The rekening you are trying to edit does not exist.');
    } 

    /*
     * Deleting rekening
     */
    function remove($id_rek)
    {
        $rekening = $this->Rekening_model->get_rekening($id_rek);

        // check if the rekening exists before trying to delete it
        if(isset($rekening['id_rek']))
        {
            $this->Rekening_model->delete_rekening($id_rek);
            redirect('rekening/index');
        }
        else
            show_error('The rekening you are trying to delete does not exist.');
    }
    
}
