<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sumberdana extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sumberdana_model');
    } 

    /*
     * Listing of sumberdana
     */
    function index()
    {
        $data['sumberdana'] = $this->Sumberdana_model->get_all_sumberdana();
        
        $data['_view'] = 'sumberdana/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new sumberdana
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'jenis_sumberdana' => $this->input->post('jenis_sumberdana'),
				'nama_sumberdana' => $this->input->post('nama_sumberdana'),
            );
            
            $sumberdana_id = $this->Sumberdana_model->add_sumberdana($params);
            redirect('sumberdana/index');
        }
        else
        {            
            $data['_view'] = 'sumberdana/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a sumberdana
     */
    function edit($id_sumberdana)
    {   
        // check if the sumberdana exists before trying to edit it
        $data['sumberdana'] = $this->Sumberdana_model->get_sumberdana($id_sumberdana);
        
        if(isset($data['sumberdana']['id_sumberdana']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'jenis_sumberdana' => $this->input->post('jenis_sumberdana'),
					'nama_sumberdana' => $this->input->post('nama_sumberdana'),
                );

                $this->Sumberdana_model->update_sumberdana($id_sumberdana,$params);            
                redirect('sumberdana/index');
            }
            else
            {
                $data['_view'] = 'sumberdana/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The sumberdana you are trying to edit does not exist.');
    } 

    /*
     * Deleting sumberdana
     */
    function remove($id_sumberdana)
    {
        $sumberdana = $this->Sumberdana_model->get_sumberdana($id_sumberdana);

        // check if the sumberdana exists before trying to delete it
        if(isset($sumberdana['id_sumberdana']))
        {
            $this->Sumberdana_model->delete_sumberdana($id_sumberdana);
            redirect('sumberdana/index');
        }
        else
            show_error('The sumberdana you are trying to delete does not exist.');
    }
    
}
