<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Swakelola extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Swakelola_model');
    } 

    /*
     * Listing of swakelola
     */
    function index()
    {
        $data['swakelola'] = $this->Swakelola_model->get_all_swakelola();
        
        $data['_view'] = 'swakelola/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new swakelola
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_satker' => $this->input->post('nama_satker'),
				'program' => $this->input->post('program'),
				'kegiatan' => $this->input->post('kegiatan'),
				'nama_paket' => $this->input->post('nama_paket'),
				'volume' => $this->input->post('volume'),
				'tipe_swakelola' => $this->input->post('tipe_swakelola'),
				'sumber_dana' => $this->input->post('sumber_dana'),
				'detail_dana_sw' => $this->input->post('detail_dana_sw'),
				'kecamatan' => $this->input->post('kecamatan'),
				'kelurahan' => $this->input->post('kelurahan'),
				'detail_lokasi' => $this->input->post('detail_lokasi'),
				'pagu_rup' => $this->input->post('pagu_rup'),
				'awal_pekerjaan' => $this->input->post('awal_pekerjaan'),
				'akhir_pekerjaan' => $this->input->post('akhir_pekerjaan'),
				'nama_ppk' => $this->input->post('nama_ppk'),
				'nip_ppk' => $this->input->post('nip_ppk'),
				'tanggal_terakhir_di_update' => $this->input->post('tanggal_terakhir_di_update'),
				'status_aktif' => $this->input->post('status_aktif'),
				'id_satker' => $this->input->post('id_satker'),
            );
            
            $swakelola_id = $this->Swakelola_model->add_swakelola($params);
            redirect('swakelola/index');
        }
        else
        {            
            $data['_view'] = 'swakelola/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a swakelola
     */
    function edit($id_p_swakelola)
    {   
        // check if the swakelola exists before trying to edit it
        $data['swakelola'] = $this->Swakelola_model->get_swakelola($id_p_swakelola);
        
        if(isset($data['swakelola']['id_p_swakelola']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_satker' => $this->input->post('nama_satker'),
					'program' => $this->input->post('program'),
					'kegiatan' => $this->input->post('kegiatan'),
					'nama_paket' => $this->input->post('nama_paket'),
					'volume' => $this->input->post('volume'),
					'tipe_swakelola' => $this->input->post('tipe_swakelola'),
					'sumber_dana' => $this->input->post('sumber_dana'),
					'detail_dana_sw' => $this->input->post('detail_dana_sw'),
					'kecamatan' => $this->input->post('kecamatan'),
					'kelurahan' => $this->input->post('kelurahan'),
					'detail_lokasi' => $this->input->post('detail_lokasi'),
					'pagu_rup' => $this->input->post('pagu_rup'),
					'awal_pekerjaan' => $this->input->post('awal_pekerjaan'),
					'akhir_pekerjaan' => $this->input->post('akhir_pekerjaan'),
					'nama_ppk' => $this->input->post('nama_ppk'),
					'nip_ppk' => $this->input->post('nip_ppk'),
					'tanggal_terakhir_di_update' => $this->input->post('tanggal_terakhir_di_update'),
					'status_aktif' => $this->input->post('status_aktif'),
					'id_satker' => $this->input->post('id_satker'),
                );

                $this->Swakelola_model->update_swakelola($id_p_swakelola,$params);            
                redirect('swakelola/index');
            }
            else
            {
                $data['_view'] = 'swakelola/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The swakelola you are trying to edit does not exist.');
    } 

    /*
     * Deleting swakelola
     */
    function remove($id_p_swakelola)
    {
        $swakelola = $this->Swakelola_model->get_swakelola($id_p_swakelola);

        // check if the swakelola exists before trying to delete it
        if(isset($swakelola['id_p_swakelola']))
        {
            $this->Swakelola_model->delete_swakelola($id_p_swakelola);
            redirect('swakelola/index');
        }
        else
            show_error('The swakelola you are trying to delete does not exist.');
    }
    
}
