<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tr_belanja_rekening extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tr_belanja_rekening_model');
    } 

    /*
     * Listing of tr_belanja_rekening
     */
    function index()
    {
        $data['tr_belanja_rekening'] = $this->Tr_belanja_rekening_model->get_all_tr_belanja_rekening();
        
        $data['_view'] = 'tr_belanja_rekening/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tr_belanja_rekening
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_keterangan' => $this->input->post('id_keterangan'),
				'Kd_Rek_1' => $this->input->post('Kd_Rek_1'),
				'Kd_Rek_2' => $this->input->post('Kd_Rek_2'),
				'Kd_Rek_3' => $this->input->post('Kd_Rek_3'),
				'Kd_Rek_4' => $this->input->post('Kd_Rek_4'),
				'Kd_Rek_5' => $this->input->post('Kd_Rek_5'),
            );
            
            $tr_belanja_rekening_id = $this->Tr_belanja_rekening_model->add_tr_belanja_rekening($params);
            redirect('tr_belanja_rekening/index');
        }
        else
        {
			$this->load->model('_keterangan_model');
			$data['all__keterangan'] = $this->_keterangan_model->get_all__keterangan();

			$this->load->model('Ref_rek_1_model');
			$data['all_ref_rek_1'] = $this->Ref_rek_1_model->get_all_ref_rek_1();

			$this->load->model('Ref_rek_2_model');
			$data['all_ref_rek_2'] = $this->Ref_rek_2_model->get_all_ref_rek_2();

			$this->load->model('Ref_rek_3_model');
			$data['all_ref_rek_3'] = $this->Ref_rek_3_model->get_all_ref_rek_3();

			$this->load->model('Ref_rek_4_model');
			$data['all_ref_rek_4'] = $this->Ref_rek_4_model->get_all_ref_rek_4();

			$this->load->model('Ref_rek_5_model');
			$data['all_ref_rek_5'] = $this->Ref_rek_5_model->get_all_ref_rek_5();
            
            $data['_view'] = 'tr_belanja_rekening/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tr_belanja_rekening
     */
    function edit($)
    {   
        // check if the tr_belanja_rekening exists before trying to edit it
        $data['tr_belanja_rekening'] = $this->Tr_belanja_rekening_model->get_tr_belanja_rekening($);
        
        if(isset($data['tr_belanja_rekening']['']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_keterangan' => $this->input->post('id_keterangan'),
					'Kd_Rek_1' => $this->input->post('Kd_Rek_1'),
					'Kd_Rek_2' => $this->input->post('Kd_Rek_2'),
					'Kd_Rek_3' => $this->input->post('Kd_Rek_3'),
					'Kd_Rek_4' => $this->input->post('Kd_Rek_4'),
					'Kd_Rek_5' => $this->input->post('Kd_Rek_5'),
                );

                $this->Tr_belanja_rekening_model->update_tr_belanja_rekening($,$params);            
                redirect('tr_belanja_rekening/index');
            }
            else
            {
				$this->load->model('_keterangan_model');
				$data['all__keterangan'] = $this->_keterangan_model->get_all__keterangan();

				$this->load->model('Ref_rek_1_model');
				$data['all_ref_rek_1'] = $this->Ref_rek_1_model->get_all_ref_rek_1();

				$this->load->model('Ref_rek_2_model');
				$data['all_ref_rek_2'] = $this->Ref_rek_2_model->get_all_ref_rek_2();

				$this->load->model('Ref_rek_3_model');
				$data['all_ref_rek_3'] = $this->Ref_rek_3_model->get_all_ref_rek_3();

				$this->load->model('Ref_rek_4_model');
				$data['all_ref_rek_4'] = $this->Ref_rek_4_model->get_all_ref_rek_4();

				$this->load->model('Ref_rek_5_model');
				$data['all_ref_rek_5'] = $this->Ref_rek_5_model->get_all_ref_rek_5();

                $data['_view'] = 'tr_belanja_rekening/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tr_belanja_rekening you are trying to edit does not exist.');
    } 

    /*
     * Deleting tr_belanja_rekening
     */
    function remove($)
    {
        $tr_belanja_rekening = $this->Tr_belanja_rekening_model->get_tr_belanja_rekening($);

        // check if the tr_belanja_rekening exists before trying to delete it
        if(isset($tr_belanja_rekening['']))
        {
            $this->Tr_belanja_rekening_model->delete_tr_belanja_rekening($);
            redirect('tr_belanja_rekening/index');
        }
        else
            show_error('The tr_belanja_rekening you are trying to delete does not exist.');
    }
    
}
