<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('User_model');
    } 

    /*
     * Listing of users
     */
    function index()
    {
        $data['users'] = $this->User_model->get_all_users();
        
        $data['_view'] = 'user/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new user
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'password' => $this->input->post('password'),
				'password_reset_key' => $this->input->post('password_reset_key'),
				'kode_urusan' => $this->input->post('kode_urusan'),
				'kode_bidang' => $this->input->post('kode_bidang'),
				'kode_unit' => $this->input->post('kode_unit'),
				'kode_sub_unit' => $this->input->post('kode_sub_unit'),
				'nama_dinas' => $this->input->post('nama_dinas'),
				'username' => $this->input->post('username'),
				'email' => $this->input->post('email'),
				'user_role' => $this->input->post('user_role'),
				'login_session_key' => $this->input->post('login_session_key'),
				'email_status' => $this->input->post('email_status'),
				'gambar' => $this->input->post('gambar'),
            );
            
            $user_id = $this->User_model->add_user($params);
            redirect('user/index');
        }
        else
        {            
            $data['_view'] = 'user/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a user
     */
    function edit($id_satker)
    {   
        // check if the user exists before trying to edit it
        $data['user'] = $this->User_model->get_user($id_satker);
        
        if(isset($data['user']['id_satker']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'password' => $this->input->post('password'),
					'password_reset_key' => $this->input->post('password_reset_key'),
					'kode_urusan' => $this->input->post('kode_urusan'),
					'kode_bidang' => $this->input->post('kode_bidang'),
					'kode_unit' => $this->input->post('kode_unit'),
					'kode_sub_unit' => $this->input->post('kode_sub_unit'),
					'nama_dinas' => $this->input->post('nama_dinas'),
					'username' => $this->input->post('username'),
					'email' => $this->input->post('email'),
					'user_role' => $this->input->post('user_role'),
					'login_session_key' => $this->input->post('login_session_key'),
					'email_status' => $this->input->post('email_status'),
					'gambar' => $this->input->post('gambar'),
                );

                $this->User_model->update_user($id_satker,$params);            
                redirect('user/index');
            }
            else
            {
                $data['_view'] = 'user/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The user you are trying to edit does not exist.');
    } 

    /*
     * Deleting user
     */
    function remove($id_satker)
    {
        $user = $this->User_model->get_user($id_satker);

        // check if the user exists before trying to delete it
        if(isset($user['id_satker']))
        {
            $this->User_model->delete_user($id_satker);
            redirect('user/index');
        }
        else
            show_error('The user you are trying to delete does not exist.');
    }
    
}
