<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Kec_kel_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get kec_kel by id_kelurahan
     */
    function get_kec_kel($id_kelurahan)
    {
        return $this->db->get_where('kec_kel',array('id_kelurahan'=>$id_kelurahan))->row_array();
    }
        
    /*
     * Get all kec_kel
     */
    function get_all_kec_kel()
    {
        $this->db->order_by('id_kelurahan', 'desc');
        return $this->db->get('kec_kel')->result_array();
    }
        
    /*
     * function to add new kec_kel
     */
    function add_kec_kel($params)
    {
        $this->db->insert('kec_kel',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update kec_kel
     */
    function update_kec_kel($id_kelurahan,$params)
    {
        $this->db->where('id_kelurahan',$id_kelurahan);
        return $this->db->update('kec_kel',$params);
    }
    
    /*
     * function to delete kec_kel
     */
    function delete_kec_kel($id_kelurahan)
    {
        return $this->db->delete('kec_kel',array('id_kelurahan'=>$id_kelurahan));
    }
}
