<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lokasi_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lokasi by id_lokasi
     */
    function get_lokasi($id_lokasi)
    {
        return $this->db->get_where('lokasi',array('id_lokasi'=>$id_lokasi))->row_array();
    }
        
    /*
     * Get all lokasi
     */
    function get_all_lokasi()
    {
        $this->db->order_by('id_lokasi', 'desc');
        return $this->db->get('lokasi')->result_array();
    }
        
    /*
     * function to add new lokasi
     */
    function add_lokasi($params)
    {
        $this->db->insert('lokasi',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lokasi
     */
    function update_lokasi($id_lokasi,$params)
    {
        $this->db->where('id_lokasi',$id_lokasi);
        return $this->db->update('lokasi',$params);
    }
    
    /*
     * function to delete lokasi
     */
    function delete_lokasi($id_lokasi)
    {
        return $this->db->delete('lokasi',array('id_lokasi'=>$id_lokasi));
    }
}
