<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Penyedium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get penyedium by id_p_progress
     */
    function get_penyedium($id_p_progress)
    {
        return $this->db->get_where('penyedia',array('id_p_progress'=>$id_p_progress))->row_array();
    }
        
    /*
     * Get all penyedia
     */
    function get_all_penyedia()
    {
        $this->db->order_by('id_p_progress', 'desc');
        return $this->db->get('penyedia')->result_array();
    }
        
    /*
     * function to add new penyedium
     */
    function add_penyedium($params)
    {
        $this->db->insert('penyedia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update penyedium
     */
    function update_penyedium($id_p_progress,$params)
    {
        $this->db->where('id_p_progress',$id_p_progress);
        return $this->db->update('penyedia',$params);
    }
    
    /*
     * function to delete penyedium
     */
    function delete_penyedium($id_p_progress)
    {
        return $this->db->delete('penyedia',array('id_p_progress'=>$id_p_progress));
    }
}
