<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Progres_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get progres by id_progress
     */
    function get_progres($id_progress)
    {
        return $this->db->get_where('progress',array('id_progress'=>$id_progress))->row_array();
    }
        
    /*
     * Get all progress
     */
    function get_all_progress()
    {
        $this->db->order_by('id_progress', 'desc');
        return $this->db->get('progress')->result_array();
    }
        
    /*
     * function to add new progres
     */
    function add_progres($params)
    {
        $this->db->insert('progress',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update progres
     */
    function update_progres($id_progress,$params)
    {
        $this->db->where('id_progress',$id_progress);
        return $this->db->update('progress',$params);
    }
    
    /*
     * function to delete progres
     */
    function delete_progres($id_progress)
    {
        return $this->db->delete('progress',array('id_progress'=>$id_progress));
    }
}
